feature/about-desktop
DenysTutov/goit-markup-project-group14 pull request #13
Opened 2022-01-29 19:56 UTC by Tetiana1192

доробила 3 макета

2022-01-29 22:09 UTC, DenysTutov requested changes

2022-01-29 22:09 UTC, DenysTutov commented on src/sass/components/_section-about.scss
> +p {
лучше задай класс тегу р. делать просто по тегу очень плохо.

2022-01-29 22:09 UTC, DenysTutov commented on src/sass/components/_section-about.scss
> +.container--bbb {
назови модификатор более четче. что он делает. bbb - не очень понятно

2022-01-29 22:09 UTC, DenysTutov commented on src/sass/components/_section-about.scss
> +.container--text {
назови модификатор более конкретно. выше есть похожий класс .container__text и уже можно запутаться.

2022-01-29 22:18 UTC, DenysTutov requested changes

2022-01-29 22:18 UTC, DenysTutov commented on src/partials/about.html
>      <p class="container__text">TRADITION AND LOVE</p>
правильнее было бы назвать этот класс section-about__label

2022-01-30 11:08 UTC, Tetiana1192 commented on src/sass/components/_section-about.scss
> +p {
виправила

2022-01-30 11:10 UTC, Tetiana1192 commented on src/sass/components/_section-about.scss
> +.container--bbb {
це поставила тимчасово, бо не приходила думка як назвати

2022-01-30 11:38 UTC, Tetiana1192 commented on src/sass/components/_section-about.scss
> +.container--text {
назвала container--story

2022-01-30 11:38 UTC, Tetiana1192 commented on src/sass/components/_section-about.scss
> +.container--bbb {
назвала container--production

2022-01-30 11:41 UTC, Tetiana1192 commented on src/partials/about.html
>      <p class="container__text">TRADITION AND LOVE</p>
виправила

2022-01-30 12:54 UTC, DenysTutov approved these changes

2022-01-30 12:54 UTC, merged