Origin/feature/mobile menu
DenysTutov/goit-markup-project-group14 pull request #18
Opened 2022-01-30 18:22 UTC by 61083nataliG0rdienk0

вроде сделала мобильное меню

2022-01-30 22:04 UTC, DenysTutov requested changes

2022-01-30 22:04 UTC, DenysTutov commented on src/partials/mobile-menu.html
> +            <use class="mobile-menu__icon-close" href="/images/close.svg#icon-close"></use>
в путь нужно точку добавить 
href="./images/close.svg#icon-close"

2022-01-30 23:07 UTC, 61083nataliG0rdienk0 commented on src/partials/mobile-menu.html
> +            <use class="mobile-menu__icon-close" href="/images/close.svg#icon-close"></use>
исправила

2022-01-31 07:09 UTC, DenysTutov approved these changes

2022-01-31 07:09 UTC, merged